apiVersion: v1
kind: Service
metadata:
  name: sargam-api-service
spec:
  selector:
    app: sargam-api
  ports:
  - protocol: "TCP"
    port: 8181
    targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sargam-api
spec:
  selector:
    matchLabels:
      app: sargam-api
  replicas: 4
  template:
    metadata:
      labels:
        app: sargam-api
    spec:
      containers:
      - name: sargam-api
        image: sargam-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
